# Generated by Django 3.1.5 on 2021-03-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carrera',
            field=models.CharField(default='Carrera sin especificar', max_length=90, verbose_name='Estudio la carrera'),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.CharField(default='Bienvenido a mi perfil', max_length=100, verbose_name='Mi estado es'),
        ),
    ]
